### ISSUE TITLE
change of the analysis key format

### ISSUE THREAD

**Issue by yannsay-impact** [gnoblet/impactR.analysis#11]
The analysis key format has changed because ~ is used in markdown.

The analysis key format is currently:
- analysis type @/@ analysis variable %/% analysis variable value @/@ grouping variable %/% grouping variable value
If there are two or more grouping variables it would look like that
- analysis type @/@ analysis variable %/% analysis variable value @/@ grouping variable 1 %/% grouping variable value 1 -/- grouping variable 2 %/% grouping variable value 2
Same would apply for analysis variable in case of a ratio.

There are 3 types of separators:

- @/@ will separate the top level information: analysis type, the analysis (dependent) variable information and the grouping (independent) variable
- %/% will separate the analysis and grouping information: it will separate the variable name and the variable value
- -/- will separate 2 variables in case there are multiple variable in either the analysis or grouping sets.

**Comment by gnoblet** [comment]
cc @yannsay-impact, it should be updated now.
